### ISSUE TITLE
i cant run your strategy properly

### ISSUE THREAD

**Issue by ardialamwijaya** [PGTBoos/GekkoStrategies#5]
Hi PGTART, first of all thanks for sharing your strategy i think its a great strategy. I just can't wait to implement it to live trading.
However, i have an issue that i cant figure it out, i receive error 500 , "can not read property startTime of undefined"

https://imgur.com/RbT1qL8

anyone can help me regarding this issue? any help will be much appreciated

Sorry for my bad english, thx :)

**Comment by PGTBoos** [comment]
The image isn't clear sharp perhaps upload it elsewhere ? 
On which strategy did you got this?
Make sure to use latest version perhaps re download it as minor tweaks where made.

**Comment by PGTBoos** [comment]
closed no response and not a good error discription might have been related to gekko instead of this strategy
